name: Deploy Serverus-Bot to Server

on:
  push:
    branches:
      - main
    paths:
      - 'serverus-bot/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Transfer docker-compose.yml to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./serverus-bot"
        target: "/media/server/WareHouse/docker-containers/serverus/"
      
    - name: Transfer docker-compose.yml to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./docker-compose.yml"
        target: "/media/server/WareHouse/docker-containers/serverus/"

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /media/server/WareHouse/docker-containers/serverus
          docker compose build
          docker compose up -d

